trigger:
- main

pool:
  vmImage: 'ubuntu-latest'  # Or use 'windows-latest' depending on your needs

steps:
- task: HelmInstaller@0
  displayName: 'Install Helm'
  inputs:
    helmVersion: 'latest'

- task: KubectlInstaller@0
  displayName: 'Set up kubectl'
  inputs:
    kubectlVersion: 'latest'
    kubeConfig: $(KUBE_CONFIG)  # Path to the kubeconfig, e.g., Docker Desktop Kubeconfig

- script: |
    echo "Deploying Helm chart to Docker Desktop Kubernetes"
    helm repo add stable https://charts.helm.sh/stable
    helm repo update
    helm install myapp ./mychart  # Replace with your chart path and name
  displayName: 'Deploy Helm Chart'

