apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  type: NodePort  # Change to NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # Specify a NodePort (e.g., 30080)
  selector:
    app: guestbook
    tier: frontend
