apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend  # Make sure the selector matches your pod labels
  ports:
    - protocol: TCP
      port: 80  # Internal port for the service
      targetPort: 80  # Port inside the container
      nodePort: 30080  # Exposed port on the node
  type: NodePort  # Make the service accessible on a node's IP
