name: Deploy to Kubernetes

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Ensure you are using the self-hosted agent

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Verify Helm is available
      run: helm version  # Make sure Helm is installed and accessible

    - name: Set up Kubernetes config from GitHub Secret
      run: |
        # PowerShell script to ensure the kube directory is created and write the Kubeconfig
        $homeDirectory = [System.Environment]::GetFolderPath('UserProfile')  # C:\Users\apurva
        $kubeDirectory = Join-Path $homeDirectory '.kube'  # C:\Users\apurva\.kube

        # Create the .kube directory if it doesn't exist
        if (-not (Test-Path -Path $kubeDirectory)) {
            New-Item -Path $kubeDirectory -ItemType Directory
        }

        # Set the Kubeconfig from GitHub Secret and save it to the correct path
        $kubeConfig = "${{ secrets.KUBECONFIG }}"  # Assuming KUBECONFIG secret contains your kubeconfig
        $kubeConfigPath = Join-Path $kubeDirectory 'config'  # C:\Users\apurva\.kube\config
        Set-Content -Path $kubeConfigPath -Value $kubeConfig

    - name: Verify Kubernetes connection
      run: |
        kubectl cluster-info  # Verify that kubectl can connect to the cluster

    - name: Install Helm Chart
      run: |
        helm repo add stable https://charts.helm.sh/stable  # Add Helm repo (if required)
        helm repo update  # Update the Helm repositories
        helm install myapp ./k8-app  # Path to the chart is './k8-app'

    - name: Wait for Kubernetes Pods to be ready
      run: |
        kubectl rollout status deployment/redis-leader  # Replace 'redis-leader' with your deployment name

    - name: Check helm deployment
      run: |
        Invoke-WebRequest http://localhost:30080/ -UseBasicParsing  # Check if the service is running correctly
