name: Deploy to Kubernetes

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Ensure you are using the self-hosted agent

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Verify Helm is available
      run: helm version  # Make sure Helm is installed and accessible

    - name: Set up Kubernetes config from GitHub Secret
      run: |
        # mkdir -p ~/.kube  # Create the kube directory if it doesn't exist
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config  # Set Kubeconfig from GitHub secret

    - name: Verify Kubernetes connection
      run: |
        kubectl cluster-info  # Verify that kubectl can connect to the cluster

    - name: Install Helm Chart
      run: |
        helm repo add stable https://charts.helm.sh/stable  # Add Helm repo (if required)
        helm repo update  # Update the Helm repositories
        helm install myapp ./k8-app  # Path to the chart is './k8-app'

    - name: Wait for Kubernetes Pods to be ready
      run: |
        kubectl rollout status deployment/redis-leader  # Replace 'myapp' with your deployment name
   
    - name: Delete Helm Chart after 30 seconds
      run: |
        helm uninstall myapp  # Delete the Helm chart after confirming accessibility    
